import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdir, mkdtemp, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import sharp from 'sharp';
import { setTimeout as delay } from 'node:timers/promises';
import { createTimewayServer } from '../server.mjs';
import { newPublication } from '../public/publish.js';

test('兑换物品发布、即时扣款、重复请求、通知及持久保存', async (t) => {
  await mkdir('.cache', { recursive: true });
  const directory = await mkdtemp('.cache/redeem-api-');
  const options = { environment: 'test', databasePath: join(directory, 'test.sqlite'), offerCoverDirectory: join(directory, 'covers') };
  const server = createTimewayServer(options);
  server.listen(0, '127.0.0.1');
  await once(server, 'listening');
  t.after(() => new Promise((resolve) => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const login = async (role) => {
    const response = await fetch(base + '/api/auth/demo-login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role, account: role, password: 'timeway123' }) });
    assert.equal(response.status, 200);
    return { ...(await response.json()), cookie: response.headers.get('set-cookie').split(';')[0] };
  };
  const org = await login('requester');
  const vol = await login('volunteer');
  const call = async (session, path, method = 'GET', body, key) => {
    const response = await fetch(base + '/api' + path, { method, headers: { Cookie: session.cookie, 'X-CSRF-Token': session.csrf, 'Content-Type': 'application/json', ...(key ? { 'Idempotency-Key': key } : {}) }, body: body ? JSON.stringify(body) : undefined });
    return { status: response.status, data: await response.json() };
  };
  const content = (await readFile('public/images/hall-housework.webp')).toString('base64');
  assert.equal((await call(vol, '/offer-covers', 'POST', { content })).status, 403);
  assert.equal((await fetch(base + '/api/offer-covers/missing')).status, 401);
  assert.equal((await call(org, '/offer-covers', 'POST', { content: '' })).status, 400);
  assert.equal((await call(org, '/offer-covers', 'POST', { content: 'A'.repeat(4194308) })).status, 413);
  const upload = await call(org, '/offer-covers', 'POST', { content });
  assert.equal(upload.status, 200);
  assert.equal((await call(org, '/offer-covers', 'POST', { content })).data.id, upload.data.id);
  const imageUrl = base + upload.data.url;
  assert.equal((await fetch(imageUrl, { headers: { Cookie: vol.cookie } })).status, 403);
  const originalImage = await fetch(imageUrl, { headers: { Cookie: org.cookie } });
  assert.equal(originalImage.status, 200);
  const metadata = await sharp(Buffer.from(await originalImage.arrayBuffer())).metadata();
  assert.equal(metadata.format, 'webp');
  assert.ok(metadata.width <= 1600 && metadata.height <= 1600);
  assert.equal(metadata.exif, undefined);
  for (const format of ['png', 'jpeg']) {
    const picture = await sharp(Buffer.from(content, 'base64')).toFormat(format).toBuffer();
    const result = await call(org, '/offer-covers', 'POST', { content: picture.toString('base64') });
    assert.equal(result.status, 200, format);
  }
  const data = { kind: 'redeem', itemName: '大米', title: '社区生活包', specification: '大米 5kg／袋，每份 1 袋', minutes: 90, coverId: upload.data.id };
  for (const invalid of [{ itemName: '' }, { title: '' }, { specification: '' }, { offerType: 'service' }, { minutes: 0 }, { minutes: 1441 }, { minutes: 1.5 }]) {
    const result = await call(org, '/tasks', 'POST', { ...data, ...invalid });
    assert.equal(result.status, 400, JSON.stringify(result));
  }
  assert.equal((await call(org, '/tasks', 'POST', { ...data, coverId: 'missing' })).status, 403);
  const created = await call(org, '/tasks', 'POST', data, 'redeem-publish-repeat');
  assert.equal(created.status, 200, JSON.stringify(created));
  assert.equal(created.data.offerType, 'goods');
  assert.equal(created.data.specification, data.specification);
  assert.equal(created.data.remaining, null);
  assert.equal(created.data.start, null);
  assert.equal(created.data.deadline, null);
  assert.equal(created.data.itemName, '大米');
  assert.equal((await call(org, '/tasks', 'POST', data, 'redeem-publish-repeat')).data.id, created.data.id);
  assert.equal((await fetch(imageUrl, { headers: { Cookie: vol.cookie } })).status, 200);
  const listed = await call(vol, '/tasks?kind=redeem');
  assert.equal(listed.data.find((item) => item.id === created.data.id).coverId, upload.data.id);
  const detail = await call(vol, `/tasks/${created.data.id}`);
  assert.equal(detail.data.itemName, data.itemName);
  assert.equal((await call(vol, `/tasks/${created.data.id}/book`, 'POST', { recipient: '领取人', phone: '13800000002', consent: true })).status, 409);
  const updated = await call(org, `/tasks/${created.data.id}`, 'PUT', { ...data, revision: created.data.revision, title: '爱心生活包', specification: '大米 5kg／袋，独立包装' });
  assert.equal(updated.status, 200);
  assert.equal(updated.data.revision, 2);
  const minimal = await call(org, '/tasks', 'POST', { kind: 'redeem', itemName: '纸巾', title: '爱心纸巾一提', specification: '3 包／提', minutes: 10 });
  assert.equal(minimal.status, 200);
  assert.equal(minimal.data.displayStatus, 'published');
  assert.equal((await call(org, `/tasks/${minimal.data.id}/action`, 'POST', { action: 'pause' })).status, 200);
  assert.equal((await call(org, `/tasks/${minimal.data.id}/action`, 'POST', { action: 'resume' })).status, 200);
  assert.equal((await call(vol, `/tasks/${minimal.data.id}`, 'DELETE', {})).status, 403);
  assert.equal((await fetch(base + `/api/tasks/${minimal.data.id}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status, 401);
  assert.equal((await call(org, `/tasks/${minimal.data.id}`, 'DELETE', {})).status, 200);
  assert.equal((await call(org, `/tasks/${minimal.data.id}`, 'DELETE', {})).status, 200);
  assert.equal((await call(org, `/tasks/${minimal.data.id}`)).status, 404);
  assert.equal((await call(org, `/tasks/${minimal.data.id}`, 'PUT', { ...minimal.data })).status, 404);
  assert.equal((await call(org, `/tasks/${minimal.data.id}/action`, 'POST', { action: 'resume' })).status, 404);
  assert.equal((await call(vol, `/tasks/${minimal.data.id}/book`, 'POST', { recipient: '申请人', phone: vol.user.phone, consent: true })).status, 409);
  assert.equal((await call(org, '/tasks?scope=mine&kind=redeem')).data.some((item) => item.id === minimal.data.id), false);
  assert.equal((await call(org, `/tasks/${created.data.id}`, 'DELETE', {})).status, 200);
  assert.equal((await fetch(imageUrl, { headers: { Cookie: vol.cookie } })).status, 403);
  const start = new Date(Date.now() + 3000).toISOString();
  const end = new Date(Date.parse(start) + 60000).toISOString();
  const help = await call(org, '/tasks', 'POST', { ...newPublication('help', org.user), title: '兑换流程验证用服务', description: '通过服务提交与机构确认验证时间账户。', address: '社区服务中心', start, end, deadline: start, minutes: 1 });
  assert.equal(help.status, 200);
  assert.equal((await call(org, `/tasks/${help.data.id}`, 'DELETE', {})).status, 400);
  const application = await call(vol, `/tasks/${help.data.id}/apply`, 'POST', {});
  assert.equal(application.status, 200);
  assert.equal((await call(org, `/applications/${application.data.id}`, 'POST', { action: 'accept' })).status, 200);
  await delay(Math.max(0, Date.parse(end) - Date.now() + 20));
  assert.equal((await call(vol, `/applications/${application.data.id}`, 'POST', { action: 'submit', start, end, content: '已完成本次流程验证服务' })).status, 200);
  assert.equal((await call(org, `/records/${application.data.id}`, 'POST', { action: 'confirm', minutes: 1, recipients: 1 })).status, 200);
  const goods = await call(org, '/tasks', 'POST', { kind: 'redeem', itemName: '便签', title: '爱心便签', specification: '1 本／份', minutes: 1, coverId: upload.data.id });
  assert.equal(goods.status, 200);
  const bookingData = { recipient: '领取人', phone: vol.user.phone, consent: true };
  assert.equal((await call(vol, `/tasks/${goods.data.id}/book`, 'POST', { ...bookingData, phone: 'abc' })).status, 400);
  assert.equal((await call(vol, '/bank')).data.accounts.find((account) => account.orgId === org.user.id).available, 1);
  const attempts = await Promise.all(Array.from({ length: 20 }, (_, i) => call(vol, `/tasks/${goods.data.id}/book`, 'POST', bookingData, `instant-redeem-${i}`)));
  const booking = attempts[0];
  for (const attempt of attempts) {
    assert.equal(attempt.status, 200, JSON.stringify(attempt));
    assert.equal(attempt.data.id, booking.data.id);
  }
  assert.equal(booking.status, 200, JSON.stringify(booking));
  assert.equal(booking.data.start, null);
  assert.equal(booking.data.itemName, '便签');
  assert.equal(booking.data.status, 'completed');
  assert.equal(booking.data.redemptionMode, 'instant');
  assert.equal(booking.data.held, 0);
  assert.equal(booking.data.charged, 1);
  assert.equal(booking.data.phone, bookingData.phone);
  assert.equal(booking.data.applicant, vol.user.name);
  assert.equal((await call(vol, `/tasks/${goods.data.id}/book`, 'POST', bookingData)).data.id, booking.data.id);
  const changing = await call(org, `/tasks/${goods.data.id}`, 'PUT', { ...goods.data, itemName: '彩色便签', revision: goods.data.revision });
  assert.equal(changing.status, 200);
  assert.equal(changing.data.hasPendingChange, false);
  const storedBooking = await call(org, `/bookings/${booking.data.id}`);
  assert.equal(storedBooking.data.itemName, '便签');
  assert.equal(storedBooking.data.phone, bookingData.phone);
  for (const action of ['accept', 'result', 'complete', 'cancel', 'task-change']) {
    assert.equal((await call(action === 'complete' ? vol : org, `/bookings/${booking.data.id}`, 'POST', { action })).status, 409);
  }
  assert.equal((await fetch(base + `/api/bookings/${booking.data.id}`)).status, 401);
  const volunteerNotices = (await call(vol, '/notices')).data.filter((notice) => notice.target === `booking/${booking.data.id}`);
  const orgNotices = (await call(org, '/notices')).data.filter((notice) => notice.target === `booking/${booking.data.id}`);
  assert.equal(volunteerNotices.length, 1);
  assert.equal(volunteerNotices[0].title, '兑换成功，请等待工作人员联系你');
  assert.equal(orgNotices.length, 1);
  assert.match(orgNotices[0].title, /请联系申请人/);
  const bank = await call(vol, '/bank');
  assert.equal(bank.data.ledger.filter((entry) => entry.kind === 'redeem').length, 1);
  const account = bank.data.accounts.find((account) => account.orgId === org.user.id);
  assert.equal(account.available, 0);
  assert.equal(account.held, 0);
  assert.equal(account.used, 1);
  assert.equal(account.contributed, 1);
  assert.equal(bank.data.bookings.filter((item) => item.taskId === goods.data.id).length, 1);
  assert.equal((await call(org, '/map?scope=mine')).data.summary.services, 1);
  assert.equal((await call(vol, `/tasks/${goods.data.id}`)).data.displayStatus, 'published');
  assert.equal((await call(org, `/tasks/${goods.data.id}`, 'DELETE', {}, 'delete-offer-repeat')).status, 200);
  assert.equal((await call(org, `/tasks/${goods.data.id}`, 'DELETE', {}, 'delete-offer-repeat')).status, 200);
  assert.equal((await call(org, `/tasks/${goods.data.id}`, 'DELETE', {})).status, 200);
  assert.equal((await call(vol, `/tasks/${goods.data.id}`)).status, 404);
  assert.equal((await call(vol, '/tasks?kind=redeem')).data.some((item) => item.id === goods.data.id), false);
  assert.equal((await call(org, '/tasks?scope=mine&kind=redeem')).data.some((item) => item.id === goods.data.id), false);
  for (const session of [org, vol]) {
    const record = await call(session, `/bookings/${booking.data.id}`);
    assert.equal(record.status, 200);
    assert.equal(record.data.phone, bookingData.phone);
    assert.equal(record.data.itemName, '便签');
    assert.equal(record.data.charged, 1);
    assert.equal(record.data.task.status, 'deleted');
    assert.equal((await call(session, '/bank')).data.bookings.some((item) => item.id === booking.data.id), true);
  }
  const afterDeletion = await call(vol, '/bank');
  assert.deepEqual(afterDeletion.data.accounts.find((item) => item.orgId === org.user.id), account);
  assert.equal(afterDeletion.data.ledger.filter((entry) => entry.kind === 'redeem').length, 1);
  assert.equal((await fetch(imageUrl, { headers: { Cookie: vol.cookie } })).status, 200);
  assert.equal((await call(org, `/audit/${goods.data.id}`)).data.filter((entry) => entry.action === 'delete').length, 1);
  const reopened = createTimewayServer(options);
  t.after(() => reopened.context.store.close());
  assert.equal(reopened.context.store.get('task', created.data.id).title, '爱心生活包');
  assert.equal(reopened.context.store.get('task', goods.data.id).status, 'deleted');
  assert.equal(reopened.context.store.get('booking', booking.data.id).redemptionMode, 'instant');
  assert.equal(reopened.context.store.get('booking', booking.data.id).charged, 1);
  assert.ok((await reopened.context.offerCovers.read(org.user, upload.data.id)).length);
});
