import { chromium, expect } from '@playwright/test';
import { once } from 'node:events';
import { mkdir, mkdtemp } from 'node:fs/promises';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { setTimeout as delay } from 'node:timers/promises';
import { createTimewayServer } from '../server.mjs';
import { newPublication } from '../public/publish.js';

await mkdir('.cache', { recursive: true });
const directory = await mkdtemp('.cache/redeem-ui-');
const server = createTimewayServer({ environment: 'test', databasePath: join(directory, 'test.sqlite'), offerCoverDirectory: join(directory, 'covers') });
server.listen(0, '127.0.0.1');
await once(server, 'listening');
const base = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const login = await context.request.post(base + '/api/auth/demo-login', { data: { role: 'requester', account: 'requester', password: 'timeway123' } });
  assert.equal(login.status(), 200);
  const orgSession = await login.json();
  const volunteer = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const volunteerLogin = await volunteer.request.post(base + '/api/auth/demo-login', { data: { role: 'volunteer', account: 'volunteer', password: 'timeway123' } });
  assert.equal(volunteerLogin.status(), 200);
  const volunteerSession = await volunteerLogin.json();
  const post = async (actor, session, path, data) => {
    const response = await actor.request.post(base + '/api' + path, { data, headers: { 'X-CSRF-Token': session.csrf } });
    assert.equal(response.status(), 200, await response.text());
    return response.json();
  };
  const start = new Date(Date.now() + 3000).toISOString();
  const end = new Date(Date.parse(start) + 60000).toISOString();
  const help = await post(context, orgSession, '/tasks', { ...newPublication('help', orgSession.user), title: '物品兑换浏览器验证服务', description: '通过完整服务提交与机构核实检查兑换流程。', address: '社区服务中心', start, end, deadline: start, minutes: 1 });
  const application = await post(volunteer, volunteerSession, `/tasks/${help.id}/apply`, {});
  await post(context, orgSession, `/applications/${application.id}`, { action: 'accept' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(base + '/#bank');
  await page.getByRole('tab', { name: '兑换物品', exact: true }).click();
  await page.getByRole('link', { name: '新增兑换物品' }).click();
  await expect(page).toHaveURL(/#publish\/redeem$/);
  const form = page.locator('#publish-form');
  await expect(form.locator('input:not([type="hidden"])')).toHaveCount(5);
  await expect(form.getByLabel('物品图片', { exact: true })).toHaveAttribute('type', 'file');
  await expect(form.locator('.offer-duration-input')).toContainText('小时');
  await expect(form.getByRole('radio')).toHaveCount(0);
  await expect(form.getByText(/领取安排|预约截止|机构联系|上传封面/)).toHaveCount(0);
  await form.getByRole('button', { name: '预览并发布', exact: true }).click();
  await expect(form.locator('[aria-invalid="true"]')).toHaveCount(3);
  await form.getByLabel('物品名称', { exact: true }).fill('大米');
  await form.getByLabel('标题', { exact: true }).fill('社区爱心好米一袋');
  await form.getByLabel('规格', { exact: true }).fill('5kg／袋，每份 1 袋');
  for (const invalid of ['0', '24.1', '0.01']) {
    await form.getByLabel('兑换所需时长', { exact: false }).fill(invalid);
    await form.getByRole('button', { name: '预览并发布', exact: true }).click();
    await expect(form.locator('.pub-field-error')).toContainText('请填写有效的小时数');
  }
  await form.getByLabel('兑换所需时长', { exact: false }).fill('0.5');
  await expect(form.locator('#offer-duration-note')).toHaveText('每份需要 0.5 小时时间权益');
  await form.getByLabel('兑换所需时长', { exact: false }).fill('1.5');
  await expect(form.locator('#offer-duration-note')).toHaveText('每份需要 1.5 小时时间权益');
  await form.getByLabel('物品图片', { exact: true }).setInputFiles('public/styles.css');
  await expect(form.locator('#offer-cover-note')).toContainText('请选择 JPG、PNG 或 WebP 图片');
  await form.getByRole('button', { name: '预览并发布', exact: true }).click();
  await expect(page.locator('#dialog')).not.toBeVisible();
  await form.getByLabel('物品图片', { exact: true }).setInputFiles('public/images/hall-companion.webp');
  await expect(form.locator('#offer-cover-note')).toHaveText('图片已上传，可点击更换');
  await expect.poll(() => form.locator('.offer-cover-preview img').evaluate((img) => img.complete && img.naturalWidth > 0)).toBe(true);
  const originalCover = await form.locator('[name="coverId"]').inputValue();
  await form.getByLabel('物品图片', { exact: true }).setInputFiles('public/images/hall-housework.webp');
  await expect(form.locator('[name="coverId"]')).not.toHaveValue(originalCover);
  await expect(form.locator('#offer-cover-note')).toHaveText('图片已上传，可点击更换');
  await form.getByRole('button', { name: '删除图片', exact: true }).click();
  await expect(form.locator('[name="coverId"]')).toHaveValue('');
  await expect(form.locator('.offer-cover-preview img')).toHaveCount(0);
  await form.getByLabel('物品图片', { exact: true }).setInputFiles('public/images/hall-housework.webp');
  await expect(form.locator('#offer-cover-note')).toHaveText('图片已上传，可点击更换');
  const coverId = await form.locator('[name="coverId"]').inputValue();
  const coverPath = `/api/offer-covers/${coverId}`;
  for (const width of [320, 390, 520, 1440]) {
    await page.setViewportSize({ width, height: 844 });
    const dimensions = await form.evaluate((element) => ({ overflow: document.documentElement.scrollWidth > window.innerWidth, titleHeight: element.elements.title.getBoundingClientRect().height, labels: [...element.querySelectorAll('label > span:first-child')].every((label) => getComputedStyle(label).display !== 'none') }));
    assert.equal(dimensions.overflow, false, `发布页面宽度 ${width}`);
    assert.equal(dimensions.labels, true);
    assert.ok(dimensions.titleHeight >= 40 && dimensions.titleHeight <= 50);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await form.getByRole('button', { name: '预览并发布', exact: true }).click();
  await expect(page.locator('#dialog')).toBeVisible();
  await expect(page.locator('#dialog')).toContainText('社区爱心好米一袋');
  await expect(page.locator('#dialog')).toContainText('5kg／袋，每份 1 袋');
  await expect(page.locator('#dialog .offer-price')).toContainText('1.5');
  await expect(page.locator('#dialog .offer-detail-cover')).toHaveAttribute('src', coverPath);
  await expect(page.locator('#dialog .offer-section')).toContainText('1.5 小时');
  await page.locator('#dialog').getByRole('button', { name: '确认发布', exact: true }).click();
  await expect(page).toHaveURL(/#task\//);
  const goodsUrl = page.url();
  const goodsId = goodsUrl.split('#task/')[1];
  const published = await (await context.request.get(base + `/api/tasks/${goodsId}`)).json();
  assert.equal(published.minutes, 90);
  assert.equal(published.coverId, coverId);
  await expect(page.locator('#app .offer-detail-cover')).toHaveAttribute('src', coverPath);
  await expect(page.locator('#app .offer-summary h1')).toHaveText('社区爱心好米一袋');
  await expect(page.locator('#app .offer-section')).toContainText('大米');
  await expect(page.locator('#app')).not.toContainText('领取安排');
  await page.getByRole('link', { name: '编辑内容', exact: true }).click();
  await expect(form.getByLabel('物品名称', { exact: true })).toHaveValue('大米');
  await expect(form.getByLabel('标题', { exact: true })).toHaveValue('社区爱心好米一袋');
  await expect(form.getByLabel('规格', { exact: true })).toHaveValue('5kg／袋，每份 1 袋');
  await expect(form.getByLabel('兑换所需时长', { exact: false })).toHaveValue('1.5');
  await expect(form.locator('.offer-cover-preview img')).toHaveAttribute('src', coverPath);
  await form.getByLabel('物品名称', { exact: true }).fill('东北大米');
  await form.getByRole('button', { name: '预览并保存修改', exact: true }).click();
  await page.locator('#dialog').getByRole('button', { name: '确认保存修改', exact: true }).click();
  await expect(page).toHaveURL(goodsUrl);
  await page.reload();
  await expect(page.locator('#app .offer-section')).toContainText('东北大米');
  await page.goto(base + '/#bank');
  await page.getByRole('tab', { name: '兑换物品', exact: true }).click();
  await expect(page.locator('.rb-offer')).toContainText('社区爱心好米一袋');
  await expect(page.locator('.rb-offer')).toContainText('东北大米');
  await expect(page.locator('.rb-offer')).not.toContainText('Invalid');
  await expect(page.locator('.rb-offer img')).toHaveAttribute('src', coverPath);
  const volunteerPage = await volunteer.newPage();
  volunteerPage.on('pageerror', (error) => errors.push(error.message));
  await volunteerPage.goto(base + '/#bank');
  const card = volunteerPage.locator(`.bank-service-card[href="#task/${goodsId}"]`);
  await expect(card).toContainText('东北大米');
  await expect(card).toContainText('可兑换');
  await expect(card.locator('img')).toHaveAttribute('src', coverPath);
  await expect.poll(() => card.locator('img').evaluate((img) => img.complete && img.naturalWidth > 0)).toBe(true);
  await card.click();
  await expect(volunteerPage.locator('.offer-summary h1')).toHaveText('社区爱心好米一袋');
  await expect(volunteerPage.getByRole('button', { name: '对应机构可用时间不足' })).toBeDisabled();
  for (const width of [320, 390, 520]) {
    await volunteerPage.setViewportSize({ width, height: 844 });
    assert.equal(await volunteerPage.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, `详情页面宽度 ${width}`);
  }
  await delay(Math.max(0, Date.parse(end) - Date.now() + 20));
  await post(volunteer, volunteerSession, `/applications/${application.id}`, { action: 'submit', start, end, content: '已完成本次兑换流程验证服务' });
  await post(context, orgSession, `/records/${application.id}`, { action: 'confirm', minutes: 1, recipients: 1 });
  const item = await post(context, orgSession, '/tasks', { kind: 'redeem', itemName: '便签', title: '爱心便签一本', specification: '1 本／份', minutes: 1, coverId });
  await volunteerPage.goto(base + `/#task/${item.id}`);
  await volunteerPage.getByRole('button', { name: '立即兑换', exact: true }).click();
  const exchange = volunteerPage.locator('#dialog');
  await expect(exchange).toContainText('确认后扣除 0.02 小时');
  await expect(exchange.locator('input')).toHaveCount(2);
  await exchange.getByLabel('申请人姓名', { exact: true }).fill('王晓明');
  await exchange.getByLabel('联系电话', { exact: true }).fill('13911112222');
  await exchange.getByRole('button', { name: '确认兑换', exact: true }).click();
  await expect(volunteerPage).toHaveURL(/#booking\//);
  const bookingUrl = volunteerPage.url();
  await expect(volunteerPage.locator('.redemption-success')).toContainText('请等待工作人员联系你');
  await expect(volunteerPage.locator('.redemption-info')).toContainText('扣除时长');
  await expect(volunteerPage.locator('.redemption-cover')).toHaveAttribute('src', coverPath);
  await volunteerPage.locator('.redemption-cover').scrollIntoViewIfNeeded();
  await expect.poll(() => volunteerPage.locator('.redemption-cover').evaluate((image) => image.complete && image.naturalWidth > 0)).toBe(true);
  await expect(volunteerPage.locator('.redemption-info .badge')).toHaveCount(0);
  await expect(volunteerPage.locator('.redemption-contact')).toContainText('王晓明');
  await expect(volunteerPage.locator('#app')).not.toContainText('确认实际结果');
  const coverUpdate = await context.request.put(base + `/api/tasks/${item.id}`, {
    data: { ...item, coverId: originalCover },
    headers: { 'X-CSRF-Token': orgSession.csrf },
  });
  assert.equal(coverUpdate.status(), 200);
  await volunteerPage.reload();
  await expect(volunteerPage.locator('.redemption-success')).toContainText('请等待工作人员联系你');
  await expect(volunteerPage.locator('.redemption-cover')).toHaveAttribute('src', coverPath);
  for (const width of [320, 390, 520]) {
    await volunteerPage.setViewportSize({ width, height: 844 });
    assert.equal(await volunteerPage.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, `志愿者兑换详情页面宽度 ${width}`);
    assert.equal(await volunteerPage.locator('.redemption-cover').evaluate((image) => image.clientWidth <= image.parentElement.clientWidth), true);
  }
  await volunteerPage.getByRole('link', { name: '查看兑换物品', exact: true }).click();
  await expect(volunteerPage.getByRole('link', { name: '查看兑换记录', exact: true })).toBeVisible();
  await expect(volunteerPage.getByRole('button', { name: '立即兑换', exact: true })).toHaveCount(0);
  await volunteerPage.goto(base + '/#bank');
  await volunteerPage.getByRole('tab', { name: '我的兑换', exact: true }).click();
  await expect(volunteerPage.locator('.bank-booking-card')).toContainText('请等待工作人员联系你');
  await expect(volunteerPage.locator('.bank-booking-card .badge')).toHaveCount(0);
  await expect(volunteerPage.locator('.bank-booking-statuses')).toHaveCount(0);
  await expect(volunteerPage.locator('.bank-booking-image')).toHaveAttribute('src', coverPath);
  await expect(volunteerPage.locator('.bank-booking-image')).toHaveAttribute('alt', '便签');
  await volunteerPage.locator('.bank-booking-image').scrollIntoViewIfNeeded();
  await expect.poll(() => volunteerPage.locator('.bank-booking-image').evaluate((image) => image.complete && image.naturalWidth > 0)).toBe(true);
  for (const width of [320, 390, 520]) {
    await volunteerPage.setViewportSize({ width, height: 844 });
    assert.equal(await volunteerPage.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, `志愿者兑换列表页面宽度 ${width}`);
    assert.equal(await volunteerPage.locator('.bank-booking-card').evaluate((card) => card.scrollWidth <= card.clientWidth), true);
  }
  await page.goto(base + '/#bank');
  await page.getByRole('tab', { name: '兑换记录', exact: true }).click();
  const requesterBooking = page.locator('.rb-booking');
  await expect(requesterBooking).toContainText('扣除时长');
  await expect(requesterBooking.locator('.badge')).toHaveCount(0);
  await expect(page.locator('.rb-booking-filters')).toHaveCount(0);
  await expect(requesterBooking).toContainText('王晓明');
  await expect(requesterBooking).toContainText('13911112222');
  await requesterBooking.click();
  await expect(page).toHaveURL(bookingUrl);
  await expect(page.locator('.redemption-success')).toHaveCount(0);
  await expect(page.locator('.redemption-info')).toContainText('便签');
  await expect(page.locator('.redemption-cover')).toHaveAttribute('src', coverPath);
  await expect(page.locator('.redemption-info .badge')).toHaveCount(0);
  await expect(page.getByRole('link', { name: '联系申请人', exact: true })).toHaveAttribute('href', 'tel:13911112222');
  await expect(page.locator('#app')).not.toContainText('接受预约');
  await expect(page.locator('#app')).not.toContainText('记录实际履约');
  await expect(page.locator('#app')).not.toContainText('已完成');
  await expect(page.locator('#app')).not.toContainText('已兑换');
  for (const width of [320, 390, 520]) {
    await page.setViewportSize({ width, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, `兑换记录页面宽度 ${width}`);
  }
  await page.getByRole('link', { name: '查看兑换物品', exact: true }).click();
  await expect(page.getByRole('heading', { name: '兑换记录', exact: true })).toHaveCount(0);
  await expect(page.locator('.booking-card')).toHaveCount(0);
  await expect(page.locator('.sticky-actions button')).toHaveCount(1);
  await expect(page.getByRole('button', { name: '删除', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '取消兑换', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '删除', exact: true }).click();
  await expect(page).toHaveURL(base + '/#bank');
  await expect(page.getByRole('tab', { name: '兑换物品', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(page.locator(`.rb-offer[href="#task/${item.id}"]`)).toHaveCount(0);
  await page.getByRole('tab', { name: '兑换记录', exact: true }).click();
  await expect(page.locator('.rb-booking')).toContainText('王晓明');
  await page.locator('.rb-booking').click();
  await expect(page.getByRole('link', { name: '联系申请人', exact: true })).toHaveAttribute('href', 'tel:13911112222');
  await expect(page.getByRole('link', { name: '查看兑换物品', exact: true })).toHaveCount(0);
  await volunteerPage.goto(base + '/#bank');
  await volunteerPage.getByRole('tab', { name: '可兑换物品', exact: true }).click();
  await expect(volunteerPage.locator(`.bank-service-card[href="#task/${item.id}"]`)).toHaveCount(0);
  await volunteerPage.getByRole('tab', { name: '我的兑换', exact: true }).click();
  await volunteerPage.locator('.bank-booking-card').click();
  await expect(volunteerPage.locator('.redemption-success')).toContainText('请等待工作人员联系你');
  await expect(volunteerPage.getByRole('link', { name: '查看兑换物品', exact: true })).toHaveCount(0);
  await page.goto(goodsUrl);
  await page.getByRole('button', { name: '删除', exact: true }).click();
  await expect(page).toHaveURL(base + '/#bank');
  await expect(page.locator('.rb-offer')).toHaveCount(0);
  assert.equal((await volunteer.request.get(base + coverPath)).status(), 200);
  await volunteerPage.reload();
  await expect(volunteerPage.locator('.redemption-cover')).toHaveAttribute('src', coverPath);
  await volunteerPage.locator('.redemption-cover').scrollIntoViewIfNeeded();
  await expect.poll(() => volunteerPage.locator('.redemption-cover').evaluate((image) => image.complete && image.naturalWidth > 0)).toBe(true);
  const balance = await (await volunteer.request.get(base + '/api/bank')).json();
  assert.equal(balance.accounts.find((account) => account.orgId === orgSession.user.id).available, 0);
  assert.equal(balance.ledger.filter((entry) => entry.kind === 'redeem').length, 1);
  const notices = await (await volunteer.request.get(base + '/api/notices')).json();
  assert.equal(notices.filter((notice) => notice.title === '兑换成功，请等待工作人员联系你').length, 1);
  assert.deepEqual(errors, []);
  console.log('物品发布、直接兑换、删除、兑换记录与联系方式保留、余额及手机布局检查通过。');
} finally {
  await browser.close();
  await new Promise((resolve) => server.close(resolve));
}
